# Site wide configuration

title: Impropooltund Andoga
locale: et_EE
description: 'Impropooltund Andoga on netisaade, kus Ando ja ta külalised räägivad Eesti impro-elust ning improviseerivad lühikesi kuuldemänge.'
logo: site-logo.jpg
search: false
url: https://pooltund.improv.ee

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      share: true
      layout: post
      categories: osad
      comments: true

# Site owner
owner:
  name: Ando Roots
  avatar: ando.jpg
  email: ando@sqroot.eu
  disqus-shortname:
  twitter: #SQrooted
  facebook: impropooltund
  github: #anroots
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #anroots
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #AndoDavidRoots
    analytics: UA-10052990-7
    verify:
    ad-client:
    ad-slot:
  bing-verify:
